### ISSUE TITLE
`#define PROFILING 0` and `-DPROFILING=0` breaks installation on latest pytorch (built from source)

### ISSUE THREAD

**Issue by dendenxu** [YuliangXiu/bvh-distance-queries#3]
Hi, Yuliang.
First of all, thank you for sharing such a nice utility repo! 

Lately I've been unsuccessful at installing `bvh-distance-queries` with the latest `pytorch` built from source.

After some digging, I found that:
Here: https://github.com/YuliangXiu/bvh-distance-queries/blob/49de18e4f0cc0aa8ae7522f33081ae1b73d1bbb0/src/bvh_cuda_op.cu#L61 you defined the `PROFILING` macro, which is used as an enum in the latest pytorch source here: 
https://github.com/pytorch/pytorch/blob/c90be037b46f58d2b120f46a1c466976f66817b5/torch/csrc/jit/runtime/graph_executor.h#L21
This causes the compiler to throw an `unexpected identifier` error at the `PROFILING` line of the pytorch source.

I suggest redefining this macro to something like `BVH_PROFILING` and change the nvcc parameters in `setup.py` correspondingly: https://github.com/YuliangXiu/bvh-distance-queries/blob/11c0043ecaae83889591b661e069e15a766cbf1c/setup.py#L67
(after performing these steps I can successfully install `bvh-distance-queries` again).

**Comment by dendenxu** [comment]
I implemented the described fix and created a PR: https://github.com/YuliangXiu/bvh-distance-queries/pull/4
Have a look if you're interested!

**Comment by YuliangXiu** [comment]
Thanks for your PR, merged it!
